# Generated by Django 4.1.7 on 2023-02-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_iru'),
    ]

    operations = [
        migrations.AddField(
            model_name='iru',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='iru',
            name='par',
            field=models.TextField(blank=True, null=True),
        ),
    ]
