# Generated by Django 4.1.7 on 2023-02-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_gallary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallary',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='gallary',
            name='img3',
        ),
    ]
